site_title = "Arxiv New Paper List"
limit_days = 14
cache_url = "https://zzwu29.github.io/Arxiv/cache.json"

[[sources]]
limit = 150
category = "cs.RO"
title = "Robotics"

[[sources]]
limit = 150
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[[sources]]
limit = 150
category = "eess.SP"
title = "Signal Processing"

[[sources]]
limit = 150
category = "eess.SY"
title = "Systems and Control"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.AI"
title = "Artificial Intelligence"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
